src/CramCoding/CramCoding.WebApp/Models/Repositories/Post/TagRepository.cs
using CramCoding.WebApp.Models.EntityClasses;
using System.Linq;

namespace CramCoding.WebApp.Models.Repositories
{
    public class PostRepository : IPostRepository
    {
        private readonly AppDbContext context;

        public PostRepository(AppDbContext context)
        {
            this.context = context;
        }

        public IQueryable<Post> GetAll()
        {
            return this.context.Post;
        }

        public Post Find(int id)
        {
            return this.context.Post.Find(id);
        }

        public void Add(Post post)
        {
            this.context.Post.Add(post);
        }

        public void Update(Post post)
        {
            this.context.Post.Update(post);
        }

        public void Delete(Post post)
        {
            this.context.Post.Remove(post);
        }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Admin/Post/AdminPostViewModel.cs
using System;

namespace CramCoding.WebApp.ViewModels.Admin.Post
{
    public class AdminPostViewModel
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset UpdatedAt { get; set; }
        public DateTimeOffset PublishedAt { get; set; }
        public bool IsVisible { get; set; }
        public int ViewsCount { get; set; }
        public string Author { get; set; }
        public string[] Categories { get; set; }
        public string[] Tags { get; set; }
        public int CommentsCount { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Admin/Post/EditPostViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.ComponentModel.DataAnnotations;

namespace CramCoding.WebApp.ViewModels.Admin.Post
{
    public class EditPostViewModel
    {
        [Required(ErrorMessage = "Fill in the header")]
        [Display(Name = "Header")]
        public string Header { get; set; }

        [Required(ErrorMessage = "Fill in the content")]
        [Display(Name = "Content")]
        public string Content { get; set; }

        [Required(ErrorMessage = "Select author")]
        [Display(Name = "Author")]
        public string SelectedAuthor { get; set; }

        public SelectListItem[] Authors { get; set; }

        [Required(ErrorMessage = "Select category")]
        [Display(Name = "Category")]
        public string SelectedCategory { get; set; }

        public SelectListItem[] Categories { get; set; }

        [Required(ErrorMessage = "Select tags")]
        [Display(Name = "Tags")]
        public string[] SelectedTags { get; set; }

        public SelectListItem[] Tags { get; set; }

        [Required(ErrorMessage = "Set publish date")]
        [Display(Name = "Publish date")]
        public DateTimeOffset? PublishedDate { get; set; }

        [Required(ErrorMessage = "Set publish time")]
        [Display(Name = "Public time")]
        public DateTimeOffset? PublishedTime { get; set; }

        [Display(Name = "Publicly visible")]
        public bool IsVisible { get; set; }

        /// <summary>
        /// Form submission datetime (UTC) as captured JS script on the client side into a hidden form field
        /// </summary>
        public DateTimeOffset? FormSumbissionDateTimeUtc { get; set; }

        /// <summary>
        /// Returns merged date and time information from <see cref="PublishedDate"/> and <see cref="PublishedTime"/>
        /// </summary>
        /// <remarks>Returns UTC datetime information</remarks>
        public DateTimeOffset? PublishedDateTimeUtc
        {
            get
            {
                if (PublishedDate == null || PublishedTime == null)
                {
                    return null;
                }

                var publishedDateTime = new DateTimeOffset(
                    PublishedDate.Value.Year,
                    PublishedDate.Value.Month,
                    PublishedDate.Value.Day,
                    PublishedTime.Value.Hour,
                    PublishedTime.Value.Minute,
                    PublishedTime.Value.Second,
                    PublishedTime.Value.Millisecond,
                    PublishedTime.Value.Offset
                );

                return publishedDateTime.ToUniversalTime();
            }
        }

        /// <summary>
        /// Name of a controller which should be used when the post is submitted
        /// </summary>
        public string SubmitController { get; set; }

        /// <summary>
        /// Name of a action method which should be used when the post is submitted
        /// </summary>
        public string SubmitAction { get; set; }

    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Admin/Post/PostViewModel.cs
using System;

namespace CramCoding.WebApp.ViewModels.Admin.Post
{
    public class PostViewModel
    {
        public int Id { get; set; }
        public string Header { get; set; }
        public string Content { get; set; }
        public DateTimeOffset CreatedAt { get; set; }
        public DateTimeOffset UpdatedAt { get; set; }
        public DateTimeOffset PublishedAt { get; set; }
        public bool IsVisible { get; set; }
        public int ViewsCount { get; set; }
        public string Author { get; set; }
        public string[] Categories { get; set; }
        public string[] Tags { get; set; }
        public int CommentsCount { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Admin/Tag/EditTagViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CramCoding.WebApp.ViewModels.Admin.Tag
{
    public class EditTagViewModel
    {
        [Required(ErrorMessage = "Fill in tag name")]
        [Display(Name = "Name")]
        public string TagName { get; set; }

        /// <summary>
        /// Name of a controller which should be used when category is submitted
        /// </summary>
        public string SubmitController { get; set; }

        /// <summary>
        /// Name of a action method which should be used when category is submitted
        /// </summary>
        public string SubmitAction { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Admin/Tag/TagViewModel.cs
namespace CramCoding.WebApp.ViewModels.Admin.Tag
{
    public class TagViewModel
    {
        public int TagId { get; set; }

        public string TagName { get; set; }

        public int PostsCount { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Home/Post/CategoryPostsViewModel.cs
using System.Collections.Generic;

namespace CramCoding.WebApp.ViewModels.Home.Post
{
    public class CategoryPostsViewModel
    {
        public string CategoryName { get; set; }
        public IEnumerable<HomePostViewModel> Posts { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/Home/Post/HomePostViewModel.cs
namespace CramCoding.WebApp.ViewModels.Home.Post
{
    public class HomePostViewModel
    {
        public string Header { get; set; }
        public string Content { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/ViewModels/PostViewModel.cs
namespace CramCoding.WebApp.ViewModels
{
    public class PostViewModel
    {
        public string Header { get; set; }
        public string Content { get; set; }
    }
}

src/CramCoding/CramCoding.WebApp/Controllers/AdminCommentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CramCoding.WebApp.Controllers
{
    /// <summary>
    /// Controller responsible for Comment administration
    /// </summary>
    [Authorize(Roles = "AdminUser")]
    public class AdminCommentController : Controller
    {
        [Route("~/AdminComment/ListComments")]
        public IActionResult ListComments()
        {
            return View();
        }
    }
}

src/CramCoding/CramCoding.WebApp/Controllers/AdminController.cs
using AutoMapper;
using CramCoding.Data.Repositories;
using CramCoding.Domain.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CramCoding.WebApp.Controllers
{
    [Authorize(Roles = "AdminUser")]
    public partial class AdminController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPostRepository postRepository;
        private readonly ICategoryRepository categoryRepository;
        private readonly ITagRepository tagRepository;
        private readonly IMapper mapper;

        public AdminController(
            UserManager<ApplicationUser> userManager,
            IPostRepository postRepository,
            ICategoryRepository categoryRepository,
            ITagRepository tagRepository,
            IMapper mapper)
        {
            this.userManager = userManager;
            this.postRepository = postRepository;
            this.categoryRepository = categoryRepository;
            this.tagRepository = tagRepository;
            this.mapper = mapper;
        }

        [Route("~/Admin")]
        [Route("~/Admin/Index")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/CramCoding/CramCoding.WebApp/Views/Admin/AddCategory.cshtml
@model EditCategoryViewModel

@{
    ViewData["Title"] = "New category";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container">

    <!-- Page Header -->
    <div class="row pb-4">
        <h1 class="display-4">New category</h1>
    </div>

    <!-- Form -->
    <form asp-action="AddCategory" method="post" role="form">

        <!-- Category Name -->
        <div class="pb-4">
            <label asp-for="CategoryName">Name</label>
            <input asp-for="CategoryName" type="text" class="form-control" />
            <span asp-validation-for="CategoryName" class="text-danger"></span>
        </div>

        <!-- Save Button -->
        <button type="submit" class="btn btn-lg btn-primary">Zapisz</button>

    </form>

</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/AddPost.cshtml
@model EditPostViewModel

@{
    ViewData["Title"] = "Nowy wpis";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container">

    <!-- Page Header -->
    <div class="row pb-2">
        <div class="col">
            <h1 class="display-4 text-center">New post</h1>
        </div>
    </div>

    <!-- Form -->
    <div class="row">

        <form asp-action="AddPost" method="post" class="row" role="form">

            <!-- Validation Summary -->
            <div asp-validation-summary="All" class="text-danger"></div>

            <!-- Post Header -->
            <div class="col-12 pb-3">
                <label asp-for="Header"></label>
                <input asp-for="Header" type="text" class="form-control" />
                <span asp-validation-for="Header" class="text-danger"></span>
            </div>

            <!-- Post Content -->
            <div class="col-12 pb-3">
                <label asp-for="Content"></label>
                <textarea asp-for="Content" class="form-control" rows="10" cols="120"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>

            <!-- Post Author -->
            <div class="col-12 pb-3">
                <label asp-for="SelectedAuthor">Author</label>
                <select asp-for="SelectedAuthor" asp-items="@Model.Authors" class="form-select">
                    <option selected disabled>Select author...</option>
                </select>
                <span asp-validation-for="SelectedAuthor" class="text-danger"></span>
            </div>

            <!-- Post Category -->
            <div class="col-12 pb-3">
                <label asp-for="SelectedCategory">Category</label>
                <select asp-for="SelectedCategory" asp-items="@Model.Categories" class="form-select">
                    <option selected disabled>Select category...</option>
                </select>
                <span asp-validation-for="SelectedCategory" class="text-danger"></span>
            </div>

            <!-- Post Tags -->
            <div class="col-12 pb-3">
                <label asp-for="SelectedTags">Tags</label>
                <select asp-for="SelectedTags" asp-items="@Model.Tags" class="form-select" multiple>
                    <option>Select tags...</option>
                </select>
                <span asp-validation-for="SelectedTags" class="text-danger"></span>
            </div>

            <!-- Published Date -->
            <div class="col-md-6">
                <label asp-for="PublishedDate">Publish date</label>
                <input asp-for="PublishedDate" type="date" class="form-control" />
                <span asp-validation-for="PublishedDate" class="text-danger"></span>
            </div>

            <!-- Published Time -->
            <div class="col-md-6 pb-4">
                <label asp-for="PublishedTime">Publish time</label>
                <input asp-for="PublishedTime" type="time" class="form-control" />
                <span asp-validation-for="PublishedTime" class="text-danger"></span>
            </div>

            <!-- Is Visible -->
            <div class="col-12 pb-5">
                <div class="form-check form-switch">
                    <input asp-for="IsVisible" type="checkbox" class="form-check-input" checked />
                    <label asp-for="IsVisible" class="form-check-label">Publicly visible</label>
                </div>
                <span asp-validation-for="IsVisible" class="text-danger"></span>
            </div>

            <!-- Save Button -->
            <div class="col-12">
                <button type="submit" onclick="updateFormSubmissionDateTime()" class="btn btn-lg btn-primary btn-block">Save</button>
            </div>

            <!-- Form Submission Datetime (UTC).
            This is a hidden input field which gets updated when the form is submitted.
            This is done by JS function which is subscribed to submit button "onlick" event.
            Form submission datetime is then passed to ViewModel via Model Binding.
            It can be further used by DB persistence logic to store post created/updated date -->
            <input hidden asp-for="FormSumbissionDateTimeUtc" type="datetime" />

        </form>

    </div>
</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/Categories.cshtml
@model CategoryViewModel[]

@{
    ViewData["Title"] = "Categories";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid">

    <!-- Page header and button -->
    <div class="row pb-2">

        <!-- Empty column (for layout purposes) -->
        <div class="col"></div>

        <!-- Page header -->
        <div class="col">
            <h1 class="display-4 text-center">Categories</h1>
        </div>

        <!-- Add category button -->
        <div class="col my-auto">
            <a type="button" asp-controller="Admin" asp-action="AddCategory" class="btn btn-lg btn-primary float-end">
                Create new
            </a>
        </div>
    </div>

    <!-- Horizontal line -->
    <div class="row pb-4">
        <hr />
    </div>

    <!-- Table of categories -->
    <div class="row">

        <!-- Empty column for explicit responsiveness -->
        <div class="col-sm-0 col-lg-1 col-xl-3"></div>

        <!-- Table -->
        <div class="col-sm-12 col-lg-10 col-xl-6">
            <table class="table table-light table-striped">
                <thead>
                    <tr class="table-dark">
                        <th>Category name</th>
                        <th>Posts count</th>
                        <th>Edit/Delete</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var category in Model)
                    {
                    <tr>
                        <td>@category.CategoryName</td>
                        <td>@category.PostsCount</td>
                        <td>
                            <div class="d-flex">

                                <!-- Edit post -->
                                <a asp-controller="Admin" asp-action="EditCategory" asp-route-id="@category.CategoryId">
                                    <i class="fa fa-edit text-dark me-5"></i>
                                </a>

                                <!-- Delete post -->
                                <a href="#">
                                    <i class="fa fa-trash-alt text-dark"></i>
                                </a>

                            </div>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>

        <!-- Empty column for explicit responsiveness -->
        <div class="col-sm-0 col-lg-1 col-xl-3"></div>

    </div>

</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="mb-2">Implementation of Admin Panel is in progress.</div>
<div>Some functionalities may not work correctly.</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/PostDetails.cshtml
@model Post

@{
    ViewData["Title"] = "Post details";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";

    const string ddResponsive = "offset-sm-2 col-sm-8 offset-md-1 col-md-9 offset-lg-0 col-lg-10";
}

<div class="container">

    <!-- Page Header and Edit/Delete Buttons -->
    <div class="row pb-2">

        <!-- Empty column (for layout purposes) -->
        <div class="col-md"></div>

        <!-- Page Header -->
        <div class="col-sm col-md">
            <h1 class="display-4 text-md-center">Post</h1>
        </div>

        <!-- Edit / Delete Buttons -->
        <div class="col-sm col-md my-auto">
            <div class="d-flex justify-content-md-end">

                <!-- Edit post -->
                <a asp-controller="Admin" asp-action="EditPost" asp-route-id=@Model.PostId class="btn btn-lg btn-outline-dark">Edit</a>

                <!-- Delete post -->
                <a data-bs-toggle="modal" data-bs-target=@($"#_DeletePostConfirmationModal-{Model.PostId}") class="btn btn-lg btn-outline-dark ms-3">Delete</a>

                <!-- Delete post confirmation modal -->
                <!-- IMPORTANT!!!: "id" attribute of the partial modal ...
                ... must match the value of the "data-bs-target" attribute -->
                <partial name="_DeletePostConfirmationModal" model=@Model.PostId />

            </div>
        </div>

    </div>

    <!-- Horizontal Line -->
    <div class="row pb-4">
        <hr />
    </div>

    <!-- Post Details -->
    <div class="row mb-3">

        <!-- ID -->
        <dl class="row mb-0">
            <dt class="col-2">Id</dt>
            <dd class="@ddResponsive">@Model.PostId</dd>
        </dl>

        <!-- Header -->
        <dl class="row mb-0">
            <dt class="col-2">Header</dt>
            <dd class="@ddResponsive">@Model.Header</dd>
        </dl>

        <!-- Content -->
        <dl class="row mb-0">
            <dt class="col-2">Content</dt>
            <dd class="@ddResponsive">
                <markdown>@Model.Content</markdown>
            </dd>
        </dl>

        <hr class="mt-2" />

        <!-- Published Date -->
        <dl class="row mb-0">
            <dt class="col-2">Published at</dt>
            <dd class="@ddResponsive">@Model.PublishedAt</dd>
        </dl>

        <!-- Updated Date -->
        <dl class="row mb-0">
            <dt class="col-2">Updated at</dt>
            <dd class="@ddResponsive">@Model.UpdatedAt</dd>
        </dl>

        <!-- Created Date -->
        <dl class="row mb-0">
            <dt class="col-2">Created at</dt>
            <dd class="@ddResponsive">@Model.CreatedAt</dd>
        </dl>

        <!-- Is Post Visible -->
        <dl class="row mb-0">
            <dt class="col-2">Publicly visible</dt>
            <dd class="@ddResponsive">@Model.IsVisible</dd>
        </dl>

        <hr class="mt-2" />

        <!-- Visits Count -->
        <dl class="row mb-0">
            <dt class="col-2">Number of visits</dt>
            <dd class="@ddResponsive">@Model.ViewsCount</dd>
        </dl>

        <!-- Comments Count -->
        <dl class="row mb-0">
            <dt class="col-2">Number of comments</dt>
            <dd class="@ddResponsive">@Model.Comments.Count</dd>
        </dl>

        <hr class="mt-2" />

        <!-- Author -->
        <dl class="row mb-0">
            <dt class="col-2">Author</dt>
            <dd class="@ddResponsive">@Model?.Author?.Email</dd>
        </dl>

        <hr class="mt-2" />

        <!-- Categories -->
        <dl class="row mb-0">
            <dt class="col-2">Categories</dt>
            <dd class="@ddResponsive">
                <ul class="list-unstyled">
                    @foreach (var category in Model.Categories)
                    {
                        <li>@category.Name</li>
                    }
                </ul>
            </dd>
        </dl>

        <hr class="mt-2" />

        <!-- Tags -->
        <dl class="row mb-0">
            <dt class="col-2">Tags</dt>
            <dd class="@ddResponsive">
                <ul class="list-unstyled">
                    @foreach (var tag in Model.Tags)
                    {
                        <li>@tag.Name</li>
                    }
                </ul>
            </dd>
        </dl>
        <hr class="mt-2" />
    </div>

    <!-- Back to List button -->
    <a type="button" asp-controller="Admin" asp-action="Posts" class="btn btn-outline-dark">Go back to List</a>

</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/Posts.cshtml
@model AdminPostViewModel[]

@{
    ViewData["Title"] = "Posts";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid">

    <!-- Page header and button -->
    <div class="row pb-2">

        <!-- Empty column (for layout purposes) -->
        <div class="col"></div>

        <!-- Page header -->
        <div class="col">
            <h1 class="display-4 text-center">Posts</h1>
        </div>

        <!-- Add post button -->
        <div class="col my-auto">
            <a type="button" asp-controller="Admin" asp-action="AddPost" class="btn btn-lg btn-primary float-end">
                Create new
            </a>
        </div>
    </div>

    <!-- Horizontal line -->
    <div class="row pb-4">
        <hr />
    </div>

    <!-- Table of posts -->
    <div class="row">
        <table class="table table-light table-striped table-hover">
            <thead>
                <tr class="table-dark">
                    <th>Header</th>
                    <th>Published at</th>
                    <th>Updated at</th>
                    <th>Created at</th>
                    <th>Visits</th>
                    <th>Edit/Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var post in Model)
                {
                    <tr onclick="showPostDetails('Admin', 'PostDetails', @post.Id)">
                        <td>@post.Header</td>
                        <td>@post.PublishedAt</td>
                        <td>@post.UpdatedAt</td>
                        <td>@post.CreatedAt</td>
                        <td>@post.ViewsCount</td>
                        <td>
                            <!-- It is important to stop propagation of the "onclick" event so that it is not bubbled to a table row -->
                            <div class="d-flex" onclick="event.stopPropagation()">

                                <!-- Edit post -->
                                <a asp-controller="Admin" asp-action="EditPost" asp-route-id="@post.Id">
                                    <i class="fa fa-edit text-dark me-5"></i>
                                </a>

                                <!-- Delete post -->
                                <a data-bs-toggle="modal" data-bs-target=@($"#_DeletePostConfirmationModal-{post.Id}")>
                                    <i class="fa fa-trash-alt text-dark"></i>
                                </a>

                                <!-- Delete post confirmation modal -->
                                <!-- IMPORTANT!!!: "id" attribute of the partial modal ...
                                ... must match the value of the "data-bs-target" attribute -->
                                <partial name="_DeletePostConfirmationModal" model=@post.Id />

                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/Tags.cshtml
@model TagViewModel[]

@{
    ViewData["Title"] = "Tags";
    Layout = "~/Views/Admin/_AdminLayout.cshtml";
}

<div class="container-fluid">

    <!-- Page header and button -->
    <div class="row pb-2">

        <!-- Empty column (for layout purposes) -->
        <div class="col"></div>

        <!-- Page header -->
        <div class="col">
            <h1 class="display-4 text-center">Tags</h1>
        </div>

        <!-- Add tag button -->
        <div class="col my-auto">
            <a type="button" asp-controller="Admin" asp-action="AddTag" class="btn btn-lg btn-primary float-end">
                Create new
            </a>
        </div>
    </div>

    <!-- Horizontal line -->
    <div class="row pb-4">
        <hr />
    </div>

    <!-- Table of tags -->
    <div class="row">

        <!-- Empty column for explicit responsiveness -->
        <div class="col-sm-0 col-lg-1 col-xl-3"></div>

        <!-- Table -->
        <div class="col-sm-12 col-lg-10 col-xl-6">
            <table class="table table-light table-striped">
                <thead>
                    <tr class="table-dark">
                        <th>Tag name</th>
                        <th>Posts count</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var tag in Model)
                    {
                        <tr>
                            <td>@tag.TagName</td>
                            <td>@tag.PostsCount</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <!-- Empty column for explicit responsiveness -->
        <div class="col-sm-0 col-lg-1 col-xl-3"></div>

    </div>

</div>

src/CramCoding/CramCoding.WebApp/Views/Admin/_AdminLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cram Coding - Admin Panel</title>
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body class="bg-light bg-gradient">

    <!-- Header -->
    <header class="d-flex flex-row align-items-center bg-dark px-4 py-2 shadow-sm">

        <!-- Label -->
        <h4 class="text-light m-0">Admin Panel</h4>

        <!-- Exit button-->
        <a type="button" asp-controller="Home" asp-action="Index" class="btn btn-lg btn-primary ms-auto px-5">Close</a>

    </header>

    <!-- Main -->
    <main class="d-flex flex-row align-items-stretch">

        <!-- Sidebar -->
        <div class="border-end bg-light shadow-sm" id="adminSidebar">
            <div class="list-group list-group-flush">
                <a asp-controller="AdminPost" asp-action="ListPosts" class="list-group-item list-group-item-action border-bottom ps-4">Posts</a>
                <a asp-controller="AdminCategory" asp-action="ListCategories" class="list-group-item list-group-item-action border-bottom ps-4">Categories</a>
                <a asp-controller="AdminTag" asp-action="ListTags" class="list-group-item list-group-item-action border-bottom ps-4">Tags</a>
                <a asp-controller="AdminComment" asp-action="ListComments" class="list-group-item list-group-item-action border-bottom ps-4">Comments</a>
                <a asp-controller="AdminUser" asp-action="ListUsers" class="list-group-item list-group-item-action border-bottom ps-4">Users</a>
            </div>
        </div>

        <!-- Content -->
        <div class="p-4 flex-fill">
            @RenderBody()
        </div>

    </main>

    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false);

</body>
</html>